# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- script: |   
    sudo apt-get update   
    sudo apt-get install libzmq3-dev

- task: GoTool@0
  inputs:
    version: '1.20'

- script: |   
    echo $GOPATH

- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: CopyFiles@2  
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'


- task: Go@0
  displayName: Execute build
  inputs:
    command: 'build'
    arguments: '-v'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Go@0
  displayName: Execute tests
  inputs:
    command: 'test'
    arguments: '-v ./...'
    workingDirectory: '$(System.DefaultWorkingDirectory)'