# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo apt-get update -y
    sudo apt-get install -y libzmq-dev
  
- task: GoTool@0
  inputs:
    version: '1.10'

- task: Go@0
  inputs:
    command: 'test'
    arguments: '-v'