[Service]
HealthCheckInterval = "10s"
Host = "localhost"
Port = 59997
ServerBindAddr = ""
StartupMsg = "device opcua started"
MaxRequestSize = 0
RequestTimeout = "5s"

[Registry]
Host = "localhost"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Clients]
[Clients.core-data]
Protocol = "http"
Host = "localhost"
Port = 59880

[Clients.core-metadata]
Protocol = "http"
Host = "localhost"
Port = 59881

[MessageQueue]
Protocol = "redis"
Host = "localhost"
Port = 6379
Type = "redis"
AuthMode = "usernamepassword"  # required for redis messagebus (secure or insecure).
SecretName = "redisdb"
PublishTopicPrefix = "edgex/events/device" # /<device-profile-name>/<device-name>/<source-name> will be added to this Publish Topic prefix
[MessageQueue.Optional]
# Default MQTT Specific options that need to be here to enable environment variable overrides of them
# Client Identifiers
ClientId = "device-opcua"
# Connection information
Qos = "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
KeepAlive = "10" # Seconds (must be 2 or greater)
Retained = "false"
AutoReconnect = "true"
ConnectTimeout = "5" # Seconds
SkipCertVerify = "false" # Only used if Cert/Key file or Cert/Key PEMblock are specified  [MessageQueue.Optional]

[Device]
DataTransform = true
MaxCmdOps = 128
MaxCmdValueLen = 256
DevicesDir = "./res/devices"
ProfilesDir = "./res/profiles"
UpdateLastConnected = false
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16
UseMessageBus = true

[SecretStore]
Type = "vault"
Host = "localhost"
Port = 8200
Path = "device-opcua/"
Protocol = "http"
RootCaCertPath = ""
ServerName = ""
TokenFile = "/tmp/edgex/secrets/device-opcua/secrets-token.json"
[SecretStore.Authentication]
AuthType = "X-Vault-Token"

[Writable]
LogLevel = "INFO"
# InsecureSecrets are required for when Redis is used for message bus
[Writable.InsecureSecrets]
[Writable.InsecureSecrets.DB]
path = "redisdb"
[Writable.InsecureSecrets.DB.Secrets]
username = ""
password = ""
[Writable.InsecureSecrets.OPCUA]
path = "credentials"
[Writable.InsecureSecrets.OPCUA.Secrets]
username = ""
password = ""

# Driver configs
[OPCUAServer]
DeviceName = ""  # Name of existing Device
Endpoint = ""# endpoint of existing Device
Policy = "None"                        # Security policy: None, Basic128Rsa15, Basic256, Basic256Sha256. Default: None
Mode = "None"                          # Security mode: None, Sign, SignAndEncrypt. Default: None
CertFile = ""                          # Path to cert.pem. Required for security mode/policy != None
KeyFile = ""                           # Path to private key.pem. Required for security mode/policy != None
CredentialsRetryTime = 120 # Seconds
CredentialsRetryWait = 1 # Seconds
ConnEstablishingRetry = 10
ConnRetryWaitTime = 5
CredentialsPath = "credentials"
[OPCUAServer.Writable]
# Device resources related to Node IDs to subscribe to (comma-separated values)
Resources = "DeviceNo,CurMachSpeed,MachSpeed,StateCurrent,UnitModeCurrent,ProdProcessedCount,ProdDefectiveCount"
